apiVersion: apps/v1
kind: Deployment
metadata:
  name: starlight-live
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starlight-live
  template:
    metadata:
      labels:
        app: starlight-live
    spec:
      volumes:
      - name: docs
        emptyDir: {}
      containers:
      - name: git-sync
        image: registry.k8s.io/git-sync/git-sync:v4.0.0
        env:
        - name: GITSYNC_REPO
          value: "https://github.com/andreisudarikov19/starlight-doc-repo.git"
        - name: GIT_SYNC_BRANCH
          value: "main"
        - name: GIT_SYNC_ROOT
          value: /git
        - name: GIT_SYNC_DEST
          value: site
        - name: GIT_SYNC_PERIOD
          value: "60s"
        volumeMounts:
        - name: docs
          mountPath: /git

      - name: astro-builder
        image: node:20-alpine
        workingDir: /git/site
        command: ["/bin/sh", "-c"]
        args:
        - |
          apk add --no-cache git && \
          while true; do \
            npm install && npx astro build; \
            echo "Build done at $(date)"; \
            sleep 60; \
          done
        volumeMounts:
        - name: docs
          mountPath: /git

      - name: static-server
        image: nginx:alpine
        volumeMounts:
        - name: docs
          mountPath: /usr/share/nginx/html
          subPath: site/dist
        ports:
        - containerPort: 80
