apiVersion: apps/v1
kind: Deployment
metadata:
  name: starlight-live
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starlight-live
  template:
    metadata:
      labels:
        app: starlight-live
    spec:
      volumes:
      - name: docs
        emptyDir: {}

      # INIT CONTAINER: git-sync
      initContainers:
      - name: git-sync
        image: registry.k8s.io/git-sync/git-sync:v4.0.0
        env:
        - name: GITSYNC_REPO
          value: "https://github.com/andreisudarikov19/starlight-doc-repo.git"
        - name: GIT_SYNC_BRANCH
          value: "main"
        - name: GIT_SYNC_ROOT
          value: /git
        - name: GIT_SYNC_DEST
          value: site
        - name: GIT_SYNC_ONE_TIME
          value: "true"
        volumeMounts:
        - name: docs
          mountPath: /git

      # MAIN CONTAINER: Astro Builder
      containers:
      - name: astro-builder
        image: node:20-bullseye
        workingDir: /git/site
        command: ["/bin/sh", "-c"]
        args:
        - |
          set -ex
          echo "Starting Astro build in /git/site..."
          ls -l /git/site
          npm install
          npx astro build
          echo "✅ Astro build complete. Holding container open for debug."
          tail -f /dev/null
        volumeMounts:
        - name: docs
          mountPath: /git

      # STATIC SERVER: NGINX
      - name: static-server
        image: nginx:alpine
        volumeMounts:
        - name: docs
          mountPath: /usr/share/nginx/html
          subPath: site/dist
        ports:
        - containerPort: 80
