apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-sync
  namespace: docs-live
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-sync
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
      labels:
        app: git-sync
    spec:
      containers:
      - name: git-sync
        image: registry.k8s.io/git-sync/git-sync:v4.0.0
        args:
          - --repo=https://github.com/andreisudarikov19/starlight-doc-repo.git
          - --branch=main
          - --root=/git
          - --dest=site
          - --period=60s
          - --http-metrics=:8080
        ports:
        - containerPort: 8080
          name: metrics
        volumeMounts:
        - name: docs
          mountPath: /git
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
      volumes:
      - name: docs
        persistentVolumeClaim:
          claimName: starlight-docs-pvc
