apiVersion: apps/v1
kind: Deployment
metadata:
  name: starlight-live
spec:
  replicas: 1            # usually 1; hot-reload rebuilds on the same pod
  selector:
    matchLabels:
      app: starlight-live
  template:
    metadata:
      labels:
        app: starlight-live
    spec:
      volumes:
      - name: docs
        emptyDir: {}      # or a PVC if you want persistence
      containers:
      - name: git-sync
        image: registry.k8s.io/git-sync/git-sync:v4.0.0
        volumeMounts:
        - name: docs
          mountPath: /git
        env:
        - name: GIT_SYNC_REPO           # public or private repo URL
          value: "https://github.com/andreisudarikov19/starlight-doc-repo.git"
        - name: GIT_SYNC_BRANCH         # 👇 branch or tag
          value: "main"
        - name: GIT_SYNC_ROOT
          value: /git
        - name: GIT_SYNC_DEST
          value: site
        - name: GIT_SYNC_PERIOD         # pull every 30 s
          value: "30s"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
      - name: alpine
        image: node:20-alpine
        workingDir: /workspace
        command: ["sh","-c","npm ci && npm run dev --host"]  # hot-reload
        ports:
        - containerPort: 4321
        volumeMounts:
        - name: docs
          mountPath: /workspace
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi