apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: docs-live
  name: starlight-docs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
